export function loadMenu() {
    const contentDiv = document.querySelector("#content");
    contentDiv.textContent = "";
    const h1 = document.createElement("h1");
    h1.textContent = `Menu`;
    contentDiv.appendChild(h1);
    const menu = document.createElement("div");
    menu.classList.add("menu");
    contentDiv.appendChild(menu);
    const apps = document.createElement("div");
    apps.classList.add("menu-section");
    menu.appendChild(apps);
    const appTitle = document.createElement("h2");
    appTitle.textContent = `APPETIZERS`;
    apps.appendChild(appTitle);
    const appItems = document.createElement("div");
    appItems.classList.add("menu-item-group");
    apps.appendChild(appItems);
    const app1Div = document.createElement("div");
    app1Div.classList.add("menu-item");
    appItems.appendChild(app1Div);
    const app1Title = document.createElement("p");
    app1Title.textContent = `Fries`;
    app1Div.appendChild(app1Title);
    const app1Price = document.createElement("p");
    app1Price.textContent = `$4.99`;
    app1Div.appendChild(app1Price);
    const app2Div = document.createElement("div");
    app2Div.classList.add("menu-item");
    appItems.appendChild(app2Div);
    const app2Title = document.createElement("p");
    app2Title.textContent = `Cheese Fries`;
    app2Div.appendChild(app2Title);
    const app2Price = document.createElement("p");
    app2Price.textContent = `$5.99`;
    app2Div.appendChild(app2Price);
    const app3Div = document.createElement("div");
    app3Div.classList.add("menu-item");
    appItems.appendChild(app3Div);
    const app3Title = document.createElement("p");
    app3Title.textContent = `Chicken Fingers`;
    app3Div.appendChild(app3Title);
    const app3Price = document.createElement("p");
    app3Price.textContent = `$8.99`;
    app3Div.appendChild(app3Price);
    const pizzas = document.createElement("div");
    pizzas.classList.add("menu-section");
    menu.appendChild(pizzas);
    const pizzaTitle = document.createElement("h2");
    pizzaTitle.textContent = `PIZZA`;
    pizzas.appendChild(pizzaTitle);
    const pizzaItems = document.createElement("div");
    pizzaItems.classList.add("menu-item-group");
    pizzas.appendChild(pizzaItems);
    const pizza1Div = document.createElement("div");
    pizza1Div.classList.add("menu-item");
    pizzaItems.appendChild(pizza1Div);
    const pizza1Title = document.createElement("p");
    pizza1Title.textContent = `BYO (Build Your Own)`;
    pizza1Div.appendChild(pizza1Title);
    const pizza1Price = document.createElement("p");
    pizza1Price.textContent = `$12.99`;
    pizza1Div.appendChild(pizza1Price);
    const pizza2Div = document.createElement("div");
    pizza2Div.classList.add("menu-item");
    pizzaItems.appendChild(pizza2Div);
    const pizza2Title = document.createElement("p");
    pizza2Title.textContent = `Neapolitan`;
    pizza2Div.appendChild(pizza2Title);
    const pizza2Price = document.createElement("p");
    pizza2Price.textContent = `$13.99`;
    pizza2Div.appendChild(pizza2Price);
    const pizza3Div = document.createElement("div");
    pizza3Div.classList.add("menu-item");
    pizzaItems.appendChild(pizza3Div);
    const pizza3Title = document.createElement("p");
    pizza3Title.textContent = `Greek`;
    pizza3Div.appendChild(pizza3Title);
    const pizza3Price = document.createElement("p");
    pizza3Price.textContent = `$16.99`;
    pizza3Div.appendChild(pizza3Price);
    const pizza4Div = document.createElement("div");
    pizza4Div.classList.add("menu-item");
    pizzaItems.appendChild(pizza4Div);
    const pizza4Title = document.createElement("p");
    pizza4Title.textContent = `Indian`;
    pizza4Div.appendChild(pizza4Title);
    const pizza4Price = document.createElement("p");
    pizza4Price.textContent = `$16.99`;
    pizza4Div.appendChild(pizza4Price);
    const pizza5Div = document.createElement("div");
    pizza5Div.classList.add("menu-item");
    pizzaItems.appendChild(pizza5Div);
    const pizza5Title = document.createElement("p");
    pizza5Title.textContent = `Mexican`;
    pizza5Div.appendChild(pizza5Title);
    const pizza5Price = document.createElement("p");
    pizza5Price.textContent = `$16.99`;
    pizza5Div.appendChild(pizza5Price);
    const sandwiches = document.createElement("div");
    sandwiches.classList.add("menu-section");
    menu.appendChild(sandwiches);
    const sandwichesTitle = document.createElement("h2");
    sandwichesTitle.textContent = `SANDWICHES`;
    sandwiches.appendChild(sandwichesTitle);
    const sandwichItems = document.createElement("div");
    sandwichItems.classList.add("menu-item-group");
    sandwiches.appendChild(sandwichItems);
    const sandwich1Div = document.createElement("div");
    sandwich1Div.classList.add("menu-item");
    sandwichItems.appendChild(sandwich1Div);
    const sandwich1Title = document.createElement("p");
    sandwich1Title.textContent = `Cheesesteak`;
    sandwich1Div.appendChild(sandwich1Title);
    const sandwich1Price = document.createElement("p");
    sandwich1Price.textContent = `$13.99`;
    sandwich1Div.appendChild(sandwich1Price);
    const sandwich2Div = document.createElement("div");
    sandwich2Div.classList.add("menu-item");
    sandwichItems.appendChild(sandwich2Div);
    const sandwich2Title = document.createElement("p");
    sandwich2Title.textContent = `Italian Hoagie`;
    sandwich2Div.appendChild(sandwich2Title);
    const sandwich2Price = document.createElement("p");
    sandwich2Price.textContent = `$13.99`;
    sandwich2Div.appendChild(sandwich2Price);
    const sandwich3Div = document.createElement("div");
    sandwich3Div.classList.add("menu-item");
    sandwichItems.appendChild(sandwich3Div);
    const sandwich3Title = document.createElement("p");
    sandwich3Title.textContent = `Torta`;
    sandwich3Div.appendChild(sandwich3Title);
    const sandwich3Price = document.createElement("p");
    sandwich3Price.textContent = `$13.99`;
    sandwich3Div.appendChild(sandwich3Price);
    const sandwich4Div = document.createElement("div");
    sandwich4Div.classList.add("menu-item");
    sandwichItems.appendChild(sandwich4Div);
    const sandwich4Title = document.createElement("p");
    sandwich4Title.textContent = `Gyro`;
    sandwich4Div.appendChild(sandwich4Title);
    const sandwich4Price = document.createElement("p");
    sandwich4Price.textContent = `$12.99`;
    sandwich4Div.appendChild(sandwich4Price);
    const drinks = document.createElement("div");
    drinks.classList.add("menu-section");
    menu.appendChild(drinks);
    const drinksTitle = document.createElement("h2");
    drinksTitle.textContent = `BEVERAGES`;
    drinks.appendChild(drinksTitle);
    const drinkItems = document.createElement("div");
    drinkItems.classList.add("menu-item-group");
    drinks.appendChild(drinkItems);
    const drink1Div = document.createElement("div");
    drink1Div.classList.add("menu-item");
    drinkItems.appendChild(drink1Div);
    const drink1Title = document.createElement("p");
    drink1Title.textContent = `Soda`;
    drink1Div.appendChild(drink1Title);
    const drink1Price = document.createElement("p");
    drink1Price.textContent = `$3.99`;
    drink1Div.appendChild(drink1Price);
    const drink2Div = document.createElement("div");
    drink2Div.classList.add("menu-item");
    drinkItems.appendChild(drink2Div);
    const drink2Title = document.createElement("p");
    drink2Title.textContent = `Lemonade`;
    drink2Div.appendChild(drink2Title);
    const drink2Price = document.createElement("p");
    drink2Price.textContent = `$3.99`;
    drink2Div.appendChild(drink2Price);
    const drink3Div = document.createElement("div");
    drink3Div.classList.add("menu-item");
    drinkItems.appendChild(drink3Div);
    const drink3Title = document.createElement("p");
    drink3Title.textContent = `Bottled Water`;
    drink3Div.appendChild(drink3Title);
    const drink3Price = document.createElement("p");
    drink3Price.textContent = `$2.99`;
    drink3Div.appendChild(drink3Price);
}